
var Module = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName ||= __filename;
  return (
function(moduleArg = {}) {
  var moduleRtn;

var m=moduleArg,aa,p,ba=new Promise((a,b)=>{aa=a;p=b}),ca="object"==typeof window,da="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,fa=Object.assign({},m),w="",ha,x;
if(ea){var fs=require("fs"),ia=require("path");w=__dirname+"/";x=a=>{a=ja(a)?new URL(a):ia.normalize(a);return fs.readFileSync(a)};ha=a=>{a=ja(a)?new URL(a):ia.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};process.argv.slice(2)}else if(ca||da)da?w=self.location.href:"undefined"!=typeof document&&document.currentScript&&(w=document.currentScript.src),_scriptName&&(w=_scriptName),w.startsWith("blob:")?w="":w=w.substr(0,w.replace(/[?#].*/,"").lastIndexOf("/")+
1),da&&(x=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=a=>ja(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{(200==d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));m.print||console.log.bind(console);
var y=m.printErr||console.error.bind(console);Object.assign(m,fa);fa=null;var A;m.wasmBinary&&(A=m.wasmBinary);var ka,la=!1,ma,B,C,na,D,F,oa,pa,qa=[],ra=[],sa=[];function ta(){var a=m.preRun.shift();qa.unshift(a)}var G=0,ua=null,H=null;function va(a){m.onAbort?.(a);a="Aborted("+a+")";y(a);la=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");p(a);throw a;}var wa=a=>a.startsWith("data:application/octet-stream;base64,"),ja=a=>a.startsWith("file://"),xa;
function ya(a){if(a==xa&&A)return new Uint8Array(A);if(x)return x(a);throw"both async and sync fetching of the wasm failed";}function za(a){return A?Promise.resolve().then(()=>ya(a)):ha(a).then(b=>new Uint8Array(b),()=>ya(a))}function Aa(a,b,c){return za(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{y(`failed to asynchronously prepare wasm: ${d}`);va(d)})}
function Ba(a,b){var c=xa;return A||"function"!=typeof WebAssembly.instantiateStreaming||wa(c)||ja(c)||ea||"function"!=typeof fetch?Aa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){y(`wasm streaming compile failed: ${e}`);y("falling back to ArrayBuffer instantiation");return Aa(c,a,b)}))}var Ca=a=>{for(;0<a.length;)a.shift()(m)};class Ea{constructor(a){this.F=a-24}}var Fa=0,Ga=0,Ha={},Ia=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function I(a){return this.fromWireType(F[a>>2])}
var J={},K={},Ja={},L,N=(a,b,c)=>{function d(f){f=c(f);if(f.length!==a.length)throw new L("Mismatched type converter count");for(var l=0;l<a.length;++l)M(a[l],f[l])}a.forEach(function(f){Ja[f]=b});var e=Array(b.length),h=[],g=0;b.forEach((f,l)=>{K.hasOwnProperty(f)?e[l]=K[f]:(h.push(f),J.hasOwnProperty(f)||(J[f]=[]),J[f].push(()=>{e[l]=K[f];++g;g===h.length&&d(e)}))});0===h.length&&d(e)},Ka,O=a=>{for(var b="";B[a];)b+=Ka[B[a++]];return b},P,La=a=>{throw new P(a);};
function Ma(a,b,c={}){var d=b.name;if(!a)throw new P(`type "${d}" must have a positive integer typeid pointer`);if(K.hasOwnProperty(a)){if(c.ka)return;throw new P(`Cannot register type '${d}' twice`);}K[a]=b;delete Ja[a];J.hasOwnProperty(a)&&(b=J[a],delete J[a],b.forEach(e=>e()))}function M(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Ma(a,b,c)}
var Na=a=>{throw new P(a.C.G.D.name+" instance already deleted");},Oa=!1,Pa=()=>{},Qa=(a,b,c)=>{if(b===c)return a;if(void 0===c.J)return null;a=Qa(a,b,c.J);return null===a?null:c.da(a)},Ra={},Q=[],Sa=()=>{for(;Q.length;){var a=Q.pop();a.C.O=!1;a["delete"]()}},R,S={},Ta=(a,b)=>{if(void 0===b)throw new P("ptr should not be undefined");for(;a.J;)b=a.S(b),a=a.J;return S[b]},Ua=(a,b)=>{if(!b.G||!b.F)throw new L("makeClassHandle requires ptr and ptrType");if(!!b.K!==!!b.H)throw new L("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return T(Object.create(a,{C:{value:b,writable:!0}}))},T=a=>{if("undefined"===typeof FinalizationRegistry)return T=b=>b,a;Oa=new FinalizationRegistry(b=>{b=b.C;--b.count.value;0===b.count.value&&(b.H?b.K.M(b.H):b.G.D.M(b.F))});T=b=>{var c=b.C;c.H&&Oa.register(b,{C:c},b);return b};Pa=b=>{Oa.unregister(b)};return T(a)};function Va(){}
var Wa=(a,b)=>Object.defineProperty(b,"name",{value:a}),Xa=(a,b,c)=>{if(void 0===a[b].I){var d=a[b];a[b]=function(...e){if(!a[b].I.hasOwnProperty(e.length))throw new P(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].I})!`);return a[b].I[e.length].apply(this,e)};a[b].I=[];a[b].I[d.T]=d}},Ya=(a,b,c)=>{if(m.hasOwnProperty(a)){if(void 0===c||void 0!==m[a].I&&void 0!==m[a].I[c])throw new P(`Cannot register public name '${a}' twice`);Xa(m,a,a);if(m.hasOwnProperty(c))throw new P(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
m[a].I[c]=b}else m[a]=b,void 0!==c&&(m[a].ta=c)},Za=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function $a(a,b,c,d,e,h,g,f){this.name=a;this.constructor=b;this.P=c;this.M=d;this.J=e;this.fa=h;this.S=g;this.da=f;this.ma=[]}var ab=(a,b,c)=>{for(;b!==c;){if(!b.S)throw new P(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.S(a);b=b.J}return a};
function bb(a,b){if(null===b){if(this.W)throw new P(`null is not a valid ${this.name}`);return 0}if(!b.C)throw new P(`Cannot pass "${cb(b)}" as a ${this.name}`);if(!b.C.F)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);return ab(b.C.F,b.C.G.D,this.D)}
function db(a,b){if(null===b){if(this.W)throw new P(`null is not a valid ${this.name}`);if(this.V){var c=this.X();null!==a&&a.push(this.M,c);return c}return 0}if(!b||!b.C)throw new P(`Cannot pass "${cb(b)}" as a ${this.name}`);if(!b.C.F)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.U&&b.C.G.U)throw new P(`Cannot convert argument of type ${b.C.K?b.C.K.name:b.C.G.name} to parameter type ${this.name}`);c=ab(b.C.F,b.C.G.D,this.D);if(this.V){if(void 0===b.C.H)throw new P("Passing raw pointer to smart pointer is illegal");
switch(this.ra){case 0:if(b.C.K===this)c=b.C.H;else throw new P(`Cannot convert argument of type ${b.C.K?b.C.K.name:b.C.G.name} to parameter type ${this.name}`);break;case 1:c=b.C.H;break;case 2:if(b.C.K===this)c=b.C.H;else{var d=b.clone();c=this.na(c,eb(()=>d["delete"]()));null!==a&&a.push(this.M,c)}break;default:throw new P("Unsupporting sharing policy");}}return c}
function fb(a,b){if(null===b){if(this.W)throw new P(`null is not a valid ${this.name}`);return 0}if(!b.C)throw new P(`Cannot pass "${cb(b)}" as a ${this.name}`);if(!b.C.F)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.C.G.U)throw new P(`Cannot convert argument of type ${b.C.G.name} to parameter type ${this.name}`);return ab(b.C.F,b.C.G.D,this.D)}
function gb(a,b,c,d,e,h,g,f,l,n,k){this.name=a;this.D=b;this.W=c;this.U=d;this.V=e;this.la=h;this.ra=g;this.aa=f;this.X=l;this.na=n;this.M=k;e||void 0!==b.J?this.toWireType=db:(this.toWireType=d?bb:fb,this.L=null)}
var hb=(a,b,c)=>{if(!m.hasOwnProperty(a))throw new L("Replacing nonexistent public symbol");void 0!==m[a].I&&void 0!==c?m[a].I[c]=b:(m[a]=b,m[a].T=c)},ib=[],jb,kb=a=>{var b=ib[a];b||(a>=ib.length&&(ib.length=a+1),ib[a]=b=jb.get(a));return b},lb=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,m["dynCall_"+a])(b,...c)):b=kb(b)(...c);return b},nb=(a,b)=>(...c)=>lb(a,b,c),U=(a,b)=>{a=O(a);var c=a.includes("j")?nb(a,b):kb(b);if("function"!=typeof c)throw new P(`unknown function pointer with signature ${a}: ${b}`);
return c},ob,qb=a=>{a=pb(a);var b=O(a);V(a);return b},rb=(a,b)=>{function c(h){e[h]||K[h]||(Ja[h]?Ja[h].forEach(c):(d.push(h),e[h]=!0))}var d=[],e={};b.forEach(c);throw new ob(`${a}: `+d.map(qb).join([", "]));},sb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(F[b+4*d>>2]);return c};function tb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].L)return!0;return!1}
function ub(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Wa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function vb(a,b,c,d,e,h){var g=b.length;if(2>g)throw new P("argTypes array size mismatch! Must at least get return value and 'this' types!");var f=null!==b[1]&&null!==c,l=tb(b);c="void"!==b[0].name;d=[a,La,d,e,Ia,b[0],b[1]];for(e=0;e<g-2;++e)d.push(b[e+2]);if(!l)for(e=f?1:2;e<b.length;++e)null!==b[e].L&&d.push(b[e].L);l=tb(b);e=b.length;var n="",k="";for(g=0;g<e-2;++g)n+=(0!==g?", ":"")+"arg"+g,k+=(0!==g?", ":"")+"arg"+g+"Wired";n=`\n        return function (${n}) {\n        if (arguments.length !== ${e-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${e-2}');\n        }`;l&&(n+="var destructors = [];\n");var r=l?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");f&&(n+="var thisWired = classParam['toWireType']("+r+", this);\n");for(g=0;g<e-2;++g)n+="var arg"+g+"Wired = argType"+g+"['toWireType']("+r+", arg"+g+");\n",q.push("argType"+g);f&&(k="thisWired"+(0<k.length?", ":
"")+k);n+=(c||h?"var rv = ":"")+"invoker(fn"+(0<k.length?", ":"")+k+");\n";if(l)n+="runDestructors(destructors);\n";else for(g=f?1:2;g<b.length;++g)h=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].L&&(n+=`${h}_dtor(${h});\n`,q.push(`${h}_dtor`));c&&(n+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [v,u]=[q,n+"}\n"];v.push(u);b=ub(v)(...d);return Wa(a,b)}
var wb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},xb=[],Y=[],eb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=xb.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}},yb={name:"emscripten::val",fromWireType:a=>{if(!a)throw new P("Cannot use deleted val. handle = "+a);var b=Y[a];9<a&&0===--Y[a+1]&&(Y[a]=void 0,xb.push(a));return b},toWireType:(a,b)=>eb(b),argPackAdvance:8,readValueFromPointer:I,L:null},cb=a=>{if(null===a)return"null";
var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},zb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(oa[c>>2])};case 8:return function(c){return this.fromWireType(pa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ab=(a,b,c)=>{switch(b){case 1:return c?d=>ma[d]:d=>B[d];case 2:return c?d=>C[d>>1]:d=>na[d>>1];case 4:return c?d=>D[d>>2]:d=>F[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Bb="undefined"!=
typeof TextDecoder?new TextDecoder:void 0,Cb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Db=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&na[c];)++c;c<<=1;if(32<c-a&&Cb)return Cb.decode(B.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=C[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Eb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)C[b>>1]=a.charCodeAt(e),b+=2;C[b>>1]=0;return b-d},Fb=a=>2*a.length,Gb=(a,b)=>
{for(var c=0,d="";!(c>=b/4);){var e=D[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Hb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var g=a.charCodeAt(++e);h=65536+((h&1023)<<10)|g&1023}D[b>>2]=h;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},Ib=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b};
L=m.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Jb=Array(256),Kb=0;256>Kb;++Kb)Jb[Kb]=String.fromCharCode(Kb);Ka=Jb;P=m.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Va.prototype,{isAliasOf:function(a){if(!(this instanceof Va&&a instanceof Va))return!1;var b=this.C.G.D,c=this.C.F;a.C=a.C;var d=a.C.G.D;for(a=a.C.F;b.J;)c=b.S(c),b=b.J;for(;d.J;)a=d.S(a),d=d.J;return b===d&&c===a},clone:function(){this.C.F||Na(this);if(this.C.R)return this.C.count.value+=1,this;var a=T,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.C;a=a(c.call(b,d,{C:{value:{count:e.count,O:e.O,R:e.R,F:e.F,G:e.G,H:e.H,K:e.K}}}));a.C.count.value+=1;a.C.O=!1;return a},["delete"](){this.C.F||
Na(this);if(this.C.O&&!this.C.R)throw new P("Object already scheduled for deletion");Pa(this);var a=this.C;--a.count.value;0===a.count.value&&(a.H?a.K.M(a.H):a.G.D.M(a.F));this.C.R||(this.C.H=void 0,this.C.F=void 0)},isDeleted:function(){return!this.C.F},deleteLater:function(){this.C.F||Na(this);if(this.C.O&&!this.C.R)throw new P("Object already scheduled for deletion");Q.push(this);1===Q.length&&R&&R(Sa);this.C.O=!0;return this}});m.getInheritedInstanceCount=()=>Object.keys(S).length;
m.getLiveInheritedInstances=()=>{var a=[],b;for(b in S)S.hasOwnProperty(b)&&a.push(S[b]);return a};m.flushPendingDeletes=Sa;m.setDelayFunction=a=>{R=a;Q.length&&R&&R(Sa)};
Object.assign(gb.prototype,{ga(a){this.aa&&(a=this.aa(a));return a},Z(a){this.M?.(a)},argPackAdvance:8,readValueFromPointer:I,fromWireType:function(a){function b(){return this.V?Ua(this.D.P,{G:this.la,F:c,K:this,H:a}):Ua(this.D.P,{G:this,F:a})}var c=this.ga(a);if(!c)return this.Z(a),null;var d=Ta(this.D,c);if(void 0!==d){if(0===d.C.count.value)return d.C.F=c,d.C.H=a,d.clone();d=d.clone();this.Z(a);return d}d=this.D.fa(c);d=Ra[d];if(!d)return b.call(this);d=this.U?d.ba:d.pointerType;var e=Qa(c,this.D,
d.D);return null===e?b.call(this):this.V?Ua(d.D.P,{G:d,F:e,K:this,H:a}):Ua(d.D.P,{G:d,F:e})}});ob=m.UnboundTypeError=((a,b)=>{var c=Wa(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
Y.push(0,1,void 0,1,null,1,!0,1,!1,1);m.count_emval_handles=()=>Y.length/2-5-xb.length;
var Mb={d:(a,b,c)=>{var d=new Ea(a);F[d.F+16>>2]=0;F[d.F+4>>2]=b;F[d.F+8>>2]=c;Fa=a;Ga++;throw Fa;},q:()=>{va("")},m:a=>{var b=Ha[a];delete Ha[a];var c=b.X,d=b.M,e=b.$,h=e.map(g=>g.ja).concat(e.map(g=>g.pa));N([a],h,g=>{var f={};e.forEach((l,n)=>{var k=g[n],r=l.ha,q=l.ia,v=g[n+e.length],u=l.oa,t=l.qa;f[l.ea]={read:E=>k.fromWireType(r(q,E)),write:(E,W)=>{var z=[];u(t,E,v.toWireType(z,W));Ia(z)}}});return[{name:b.name,fromWireType:l=>{var n={},k;for(k in f)n[k]=f[k].read(l);d(l);return n},toWireType:(l,
n)=>{for(var k in f)if(!(k in n))throw new TypeError(`Missing field: "${k}"`);var r=c();for(k in f)f[k].write(r,n[k]);null!==l&&l.push(d,r);return r},argPackAdvance:8,readValueFromPointer:I,L:d}]})},p:()=>{},u:(a,b,c,d)=>{b=O(b);M(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,h){return h?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(B[e])},L:null})},g:(a,b,c,d,e,h,g,f,l,n,k,r,q)=>{k=O(k);h=U(e,h);f&&=U(g,f);n&&=U(l,n);q=U(r,q);var v=Za(k);Ya(v,
function(){rb(`Cannot construct ${k} due to unbound types`,[d])});N([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var t=u.D;var E=t.P}else E=Va.prototype;u=Wa(k,function(...Da){if(Object.getPrototypeOf(this)!==W)throw new P("Use 'new' to construct "+k);if(void 0===z.N)throw new P(k+" has no accessible constructor");var mb=z.N[Da.length];if(void 0===mb)throw new P(`Tried to invoke ctor of ${k} with invalid number of parameters (${Da.length}) - expected (${Object.keys(z.N).toString()}) parameters instead!`);return mb.apply(this,
Da)});var W=Object.create(E,{constructor:{value:u}});u.prototype=W;var z=new $a(k,u,W,q,t,h,f,n);if(z.J){var X;(X=z.J).Y??(X.Y=[]);z.J.Y.push(z)}t=new gb(k,z,!0,!1,!1);X=new gb(k+"*",z,!1,!1,!1);E=new gb(k+" const*",z,!1,!0,!1);Ra[a]={pointerType:X,ba:E};hb(v,u);return[t,X,E]})},f:(a,b,c,d,e,h)=>{var g=sb(b,c);e=U(d,e);N([],[a],f=>{f=f[0];var l=`constructor ${f.name}`;void 0===f.D.N&&(f.D.N=[]);if(void 0!==f.D.N[b-1])throw new P(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);f.D.N[b-1]=()=>{rb(`Cannot construct ${f.name} due to unbound types`,g)};N([],g,n=>{n.splice(1,0,null);f.D.N[b-1]=vb(l,n,null,e,h);return[]});return[]})},b:(a,b,c,d,e,h,g,f,l)=>{var n=sb(c,d);b=O(b);b=wb(b);h=U(e,h);N([],[a],k=>{function r(){rb(`Cannot call ${q} due to unbound types`,n)}k=k[0];var q=`${k.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);f&&k.D.ma.push(b);
var v=k.D.P,u=v[b];void 0===u||void 0===u.I&&u.className!==k.name&&u.T===c-2?(r.T=c-2,r.className=k.name,v[b]=r):(Xa(v,b,q),v[b].I[c-2]=r);N([],n,t=>{t=vb(q,t,k,h,g,l);void 0===v[b].I?(t.T=c-2,v[b]=t):v[b].I[c-2]=t;return[]});return[]})},t:a=>M(a,yb),k:(a,b,c)=>{b=O(b);M(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:zb(b,c),L:null})},j:(a,b,c,d,e,h,g)=>{var f=sb(b,c);a=O(a);a=wb(a);e=U(d,e);Ya(a,function(){rb(`Cannot call ${a} due to unbound types`,f)},b-1);
N([],f,l=>{l=[l[0],null].concat(l.slice(1));hb(a,vb(a,l,null,e,h,g),b-1);return[]})},c:(a,b,c,d,e)=>{b=O(b);-1===e&&(e=4294967295);e=f=>f;if(0===d){var h=32-8*c;e=f=>f<<h>>>h}var g=b.includes("unsigned")?function(f,l){return l>>>0}:function(f,l){return l};M(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:8,readValueFromPointer:Ab(b,c,0!==d),L:null})},a:(a,b,c)=>{function d(h){return new e(ma.buffer,F[h+4>>2],F[h>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,
Float64Array][b];c=O(c);M(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ka:!0})},i:a=>{M(a,yb)},l:(a,b)=>{b=O(b);var c="std::string"===b;M(a,{name:b,fromWireType:function(d){var e=F[d>>2],h=d+4;if(c)for(var g=h,f=0;f<=e;++f){var l=h+f;if(f==e||0==B[l]){if(g){var n=g;var k=B,r=n+(l-g);for(g=n;k[g]&&!(g>=r);)++g;if(16<g-n&&k.buffer&&Bb)n=Bb.decode(k.subarray(n,g));else{for(r="";n<g;){var q=k[n++];if(q&128){var v=k[n++]&63;if(192==(q&224))r+=String.fromCharCode((q&31)<<6|v);else{var u=
k[n++]&63;q=224==(q&240)?(q&15)<<12|v<<6|u:(q&7)<<18|v<<12|u<<6|k[n++]&63;65536>q?r+=String.fromCharCode(q):(q-=65536,r+=String.fromCharCode(55296|q>>10,56320|q&1023))}}else r+=String.fromCharCode(q)}n=r}}else n="";if(void 0===t)var t=n;else t+=String.fromCharCode(0),t+=n;g=l+1}}else{t=Array(e);for(f=0;f<e;++f)t[f]=String.fromCharCode(B[h+f]);t=t.join("")}V(d);return t},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var h,g="string"==typeof e;if(!(g||e instanceof Uint8Array||
e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new P("Cannot pass non-string to std::string");var f;if(c&&g)for(h=f=0;h<e.length;++h){var l=e.charCodeAt(h);127>=l?f++:2047>=l?f+=2:55296<=l&&57343>=l?(f+=4,++h):f+=3}else f=e.length;h=f;f=Lb(4+h+1);l=f+4;F[f>>2]=h;if(c&&g){if(g=l,l=h+1,h=B,0<l){l=g+l-1;for(var n=0;n<e.length;++n){var k=e.charCodeAt(n);if(55296<=k&&57343>=k){var r=e.charCodeAt(++n);k=65536+((k&1023)<<10)|r&1023}if(127>=k){if(g>=l)break;h[g++]=k}else{if(2047>=k){if(g+1>=
l)break;h[g++]=192|k>>6}else{if(65535>=k){if(g+2>=l)break;h[g++]=224|k>>12}else{if(g+3>=l)break;h[g++]=240|k>>18;h[g++]=128|k>>12&63}h[g++]=128|k>>6&63}h[g++]=128|k&63}}h[g]=0}}else if(g)for(g=0;g<h;++g){n=e.charCodeAt(g);if(255<n)throw V(l),new P("String has UTF-16 code units that do not fit in 8 bits");B[l+g]=n}else for(g=0;g<h;++g)B[l+g]=e[g];null!==d&&d.push(V,f);return f},argPackAdvance:8,readValueFromPointer:I,L(d){V(d)}})},h:(a,b,c)=>{c=O(c);if(2===b){var d=Db;var e=Eb;var h=Fb;var g=f=>na[f>>
1]}else 4===b&&(d=Gb,e=Hb,h=Ib,g=f=>F[f>>2]);M(a,{name:c,fromWireType:f=>{for(var l=F[f>>2],n,k=f+4,r=0;r<=l;++r){var q=f+4+r*b;if(r==l||0==g(q))k=d(k,q-k),void 0===n?n=k:(n+=String.fromCharCode(0),n+=k),k=q+b}V(f);return n},toWireType:(f,l)=>{if("string"!=typeof l)throw new P(`Cannot pass non-string to C++ string type ${c}`);var n=h(l),k=Lb(4+n+b);F[k>>2]=n/b;e(l,k+4,n+b);null!==f&&f.push(V,k);return k},argPackAdvance:8,readValueFromPointer:I,L(f){V(f)}})},o:(a,b,c,d,e,h)=>{Ha[a]={name:O(b),X:U(c,
d),M:U(e,h),$:[]}},n:(a,b,c,d,e,h,g,f,l,n)=>{Ha[a].$.push({ea:O(b),ja:c,ha:U(d,e),ia:h,pa:g,oa:U(f,l),qa:n})},v:(a,b)=>{b=O(b);M(a,{sa:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},s:(a,b,c)=>B.copyWithin(a,b,b+c),e:(a,b)=>{var c=K[a];if(void 0===c)throw a=`${"_emval_take_value"} has unknown type ${qb(a)}`,new P(a);a=c;a=a.readValueFromPointer(b);return eb(a)},r:()=>{va("OOM")}},Z=function(){function a(c){Z=c.exports;ka=Z.w;c=ka.buffer;m.HEAP8=ma=new Int8Array(c);m.HEAP16=C=
new Int16Array(c);m.HEAPU8=B=new Uint8Array(c);m.HEAPU16=na=new Uint16Array(c);m.HEAP32=D=new Int32Array(c);m.HEAPU32=F=new Uint32Array(c);m.HEAPF32=oa=new Float32Array(c);m.HEAPF64=pa=new Float64Array(c);jb=Z.A;ra.unshift(Z.x);G--;m.monitorRunDependencies?.(G);0==G&&(null!==ua&&(clearInterval(ua),ua=null),H&&(c=H,H=null,c()));return Z}var b={a:Mb};G++;m.monitorRunDependencies?.(G);if(m.instantiateWasm)try{return m.instantiateWasm(b,a)}catch(c){y(`Module.instantiateWasm callback failed with error: ${c}`),
p(c)}xa||=wa("msdfgen.wasm")?"msdfgen.wasm":m.locateFile?m.locateFile("msdfgen.wasm",w):w+"msdfgen.wasm";Ba(b,function(c){a(c.instance)}).catch(p);return{}}(),pb=a=>(pb=Z.y)(a),V=m._free=a=>(V=m._free=Z.z)(a),Lb=m._malloc=a=>(Lb=m._malloc=Z.B)(a),Nb;H=function Ob(){Nb||Pb();Nb||(H=Ob)};
function Pb(){function a(){if(!Nb&&(Nb=!0,m.calledRun=!0,!la)){Ca(ra);aa(m);m.onRuntimeInitialized?.();if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var b=m.postRun.shift();sa.unshift(b)}Ca(sa)}}if(!(0<G)){if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)ta();Ca(qa);0<G||(m.setStatus?(m.setStatus("Running..."),setTimeout(function(){setTimeout(function(){m.setStatus("")},1);a()},1)):a())}}
if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.pop()();Pb();moduleRtn=ba;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], () => Module);
export default Module;